'''
The various internal exceptions
'''

class ChannelAlreadyExists(Exception):
    pass
